// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf5EfaPUU-eTEVotdRUpyf0gSl1XOEU4c',
    appId: '1:367455978362:web:e6b2df21b7f66b6abe0cc3',
    messagingSenderId: '367455978362',
    projectId: 'new-moveies',
    authDomain: 'new-moveies.firebaseapp.com',
    storageBucket: 'new-moveies.appspot.com',
    measurementId: 'G-6H3MMSZ6PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjVcjhBLYx3fxWgV_JSFqNKOYNAhnPKmw',
    appId: '1:367455978362:android:2832c2a11dd7e1c0be0cc3',
    messagingSenderId: '367455978362',
    projectId: 'new-moveies',
    storageBucket: 'new-moveies.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1Q_enzqQfHiHJImhJ296D1qkz837fuDU',
    appId: '1:367455978362:ios:a5d2803fb7f34659be0cc3',
    messagingSenderId: '367455978362',
    projectId: 'new-moveies',
    storageBucket: 'new-moveies.appspot.com',
    iosBundleId: 'com.example.moviesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1Q_enzqQfHiHJImhJ296D1qkz837fuDU',
    appId: '1:367455978362:ios:52f3fffa1e72a02bbe0cc3',
    messagingSenderId: '367455978362',
    projectId: 'new-moveies',
    storageBucket: 'new-moveies.appspot.com',
    iosBundleId: 'com.example.moviesApp.RunnerTests',
  );
}
